// 73 concessionárias conforme documento de instruções
// Fonte: ANTT, ARTESP, reguladores estaduais

export const CONCESSIONARIAS_COMPLETAS = [
  // === FEDERAIS (ANTT) - 39 registros ===

  // Grupo Arteris
  {
    nome: "Autopista Fluminense",
    grupo: "Arteris",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RJ"]),
    extensaoKm: 322.10,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Autopista Litoral Sul",
    grupo: "Arteris",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SC", "PR"]),
    extensaoKm: 409.40,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Autopista Planalto Sul",
    grupo: "Arteris",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR", "SC"]),
    extensaoKm: 406.20,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Autopista Régis Bittencourt",
    grupo: "Arteris",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SP", "PR"]),
    extensaoKm: 392.00,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Grupo Triunfo
  {
    nome: "CONCEBRA (Triunfo Concebra)",
    grupo: "Triunfo",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["DF", "GO"]),
    extensaoKm: 211.60,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Trecho Goiânia-Brasília; será relicitado como Rota do Pequi (leilão ago/2026)",
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Encerrada
  {
    nome: "CONCER",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG", "RJ"]),
    extensaoKm: 184.00,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Grupo EcoRodovias
  {
    nome: "Ecovias Minas Goiás (Eco050)",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["GO", "MG"]),
    extensaoKm: 433.20,
    situacao: "ATIVO",
    canalIsentos: "isentos@eco050.com.br",
    tipoCanal: "EMAIL",
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Ecovias Capixaba",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["ES", "BA"]),
    extensaoKm: 480.20,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Ecovias Ponte (Ecoponte)",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RJ"]),
    extensaoKm: 20.40,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Ecovias Rio Minas",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RJ", "MG"]),
    extensaoKm: 733.00,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Ecovias Sul (Ecosul)",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RS"]),
    extensaoKm: 456.40,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Ecovias Araguaia",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["TO", "GO"]),
    extensaoKm: 850.70,
    situacao: "ATIVO",
    canalIsentos: "isentos.araguaia@ecovias.com.br",
    tipoCanal: "EMAIL",
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Ecovias Cerrado",
    grupo: "EcoRodovias",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG", "GO"]),
    extensaoKm: 432.60,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Outros grupos/sem grupo
  {
    nome: "Nova Rota do Oeste",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MT"]),
    extensaoKm: 858.90,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "RioSP (CCR RioSP)",
    grupo: "CCR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SP", "RJ"]),
    extensaoKm: 617.50,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Transbrasiliana",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SP"]),
    extensaoKm: 323.60,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Via Brasil BR-163",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MT", "PA"]),
    extensaoKm: 1001.20,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "ViaCosteira (CCR ViaCosteira)",
    grupo: "CCR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SC"]),
    extensaoKm: 217.30,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "ViaSul",
    grupo: "CCR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RS"]),
    extensaoKm: 465.30,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Grupo EPR
  {
    nome: "EPR Litoral Pioneiro",
    grupo: "EPR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 604.16,
    situacao: "ATIVO",
    canalIsentos: "https://www.eprltorais.com.br/isentos",
    tipoCanal: "PORTAL_MAIS_ATENDIMENTO",
    ativoParaCadastro: true,
    observacoes: "Formulário no site + WhatsApp",
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Via Araucária",
    grupo: "EPR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 471.68,
    situacao: "ATIVO",
    canalIsentos: "https://www.viaaraucaria.com.br/isentos",
    tipoCanal: "PORTAL_MAIS_ATENDIMENTO",
    ativoParaCadastro: true,
    observacoes: "Formulário no site + WhatsApp",
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Nova Dutra",
    grupo: "CCR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["SP", "RJ"]),
    extensaoKm: 402.00,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EPR Via Mineira",
    grupo: "EPR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG"]),
    extensaoKm: 232.10,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Grupo Motiva
  {
    nome: "Motiva Paraná (ex-PRVias)",
    grupo: "Motiva",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 569.00,
    situacao: "ATIVO",
    canalIsentos: "https://isentos.motivapagamentos.com.br",
    tipoCanal: "PORTAL_WEB",
    ativoParaCadastro: true,
    observacoes: "Portal com RPA Playwright",
    camposObrigatorios: JSON.stringify([
      "placa",
      "renavam",
      "cor",
      "modelo",
      "anoFabricacao",
      "anoModelo",
    ]),
  },
  {
    nome: "Motiva Pantanal",
    grupo: "Motiva",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MS"]),
    extensaoKm: 845.90,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Motiva Minas SP",
    grupo: "Motiva",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG", "SP"]),
    extensaoKm: 569.10,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Diversos
  {
    nome: "Nova 381",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG"]),
    extensaoKm: 304.00,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Via Cristais",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["GO", "MG"]),
    extensaoKm: 594.80,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // Grupo Way Brasil
  {
    nome: "Way-262",
    grupo: "Way Brasil",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG"]),
    extensaoKm: 440.60,
    situacao: "ATIVO",
    canalIsentos: "isento@way262.com.br",
    tipoCanal: "EMAIL",
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Rota Verde Goiás",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["GO"]),
    rodovias: JSON.stringify(["BR-060", "BR-452"]),
    extensaoKm: 426.20,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Cobrança a partir de 2026. Rota crítica Goiânia-Brasília.",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EPR Iguaçu",
    grupo: "EPR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 662.10,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Nova 364",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RO"]),
    extensaoKm: 686.70,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Via Bahia",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["BA"]),
    extensaoKm: 676.00,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "VIA 040",
    grupo: "Invepar",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["DF", "GO", "MG"]),
    extensaoKm: 936.80,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Assumida pelo DNIT; trecho Brasília-Cristalina em renegociação",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Rodovia do Aço",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["RJ"]),
    extensaoKm: 182.50,
    situacao: "CONTRATO_ENCERRADO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Caducidade declarada",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Elovias",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG", "RJ"]),
    extensaoKm: 218.90,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EPR Paraná",
    grupo: "EPR",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 627.52,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Way-364 (Rota Agro)",
    grupo: "Way Brasil",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["GO", "MT"]),
    extensaoKm: 490.06,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Way-153 (Rota Sertaneja)",
    grupo: "Way Brasil",
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["MG", "GO"]),
    extensaoKm: 530.60,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Via Campo",
    grupo: null,
    esfera: "FEDERAL",
    regulador: "ANTT",
    estados: JSON.stringify(["PR"]),
    extensaoKm: 432.70,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // === ESTADUAIS SP (ARTESP) - 22 registros ===

  {
    nome: "AutoBAn",
    grupo: "CCR",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "TEBE",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Intervias",
    grupo: "Arteris",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Rota das Bandeiras",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Renovias",
    grupo: "CCR",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "ViaOeste",
    grupo: "CCR",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Colinas",
    grupo: "Via Appia",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "CART",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "ViaRondon",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "SPVias",
    grupo: "CCR",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Rodovias do Tietê",
    grupo: "Via Appia",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EcoVias",
    grupo: "EcoRodovias",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EcoPistas",
    grupo: "EcoRodovias",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "CCR RodoAnel",
    grupo: "CCR",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "SPMar",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Rodoanel Norte",
    grupo: "Via Appia",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Tamoios",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Entrevias",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "ViaPaulista",
    grupo: "Arteris",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EixoSP",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "EcoNoroeste",
    grupo: "EcoRodovias",
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Novo Litoral",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "ARTESP",
    estados: JSON.stringify(["SP"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // === ESTADUAIS - Demais estados (12 registros) ===

  // MS
  {
    nome: "Way-306",
    grupo: "Way Brasil",
    esfera: "ESTADUAL",
    regulador: "Gov. MS",
    estados: JSON.stringify(["MS"]),
    rodovias: JSON.stringify(["MS-306", "BR-359"]),
    extensaoKm: 219.5,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Way-112",
    grupo: "Way Brasil",
    esfera: "ESTADUAL",
    regulador: "Gov. MS",
    estados: JSON.stringify(["MS"]),
    rodovias: JSON.stringify(["MS-112", "BR-158", "BR-436"]),
    extensaoKm: 412.4,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // MT
  {
    nome: "Via Brasil 246",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "Gov. MT (Sinfra)",
    estados: JSON.stringify(["MT"]),
    rodovias: JSON.stringify(["MT-246", "MT-343", "MT-358"]),
    extensaoKm: 233,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Rota dos Grãos",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "Gov. MT (Sinfra)",
    estados: JSON.stringify(["MT"]),
    rodovias: JSON.stringify(["MT-130"]),
    extensaoKm: 140.6,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Consórcio RDG Sinop (Lote 6 MT)",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "Gov. MT (Sinfra)",
    estados: JSON.stringify(["MT"]),
    rodovias: JSON.stringify(["MT-020", "MT-140", "MT-225", "MT-244", "MT-251"]),
    extensaoKm: 634.3,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Leiloado out/2025",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Concessionária MT-100 (Lote 1)",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "Gov. MT (Sinfra)",
    estados: JSON.stringify(["MT"]),
    rodovias: JSON.stringify(["MT-100"]),
    extensaoKm: 111.9,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Nome da concessionária a confirmar na Sinfra-MT",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Concessionária MT-320/208 (Lote 2)",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "Gov. MT (Sinfra)",
    estados: JSON.stringify(["MT"]),
    rodovias: JSON.stringify(["MT-320", "MT-208"]),
    extensaoKm: 188.2,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Nome da concessionária a confirmar na Sinfra-MT",
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // RS
  {
    nome: "EGR (Empresa Gaúcha de Rodovias)",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "EGR/DAER",
    estados: JSON.stringify(["RS"]),
    extensaoKm: 630,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    observacoes: "Pedágio público estadual, não concessionária privada. ~10-14 praças.",
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "CSG (Caminhos da Serra Gaúcha)",
    grupo: null,
    esfera: "ESTADUAL",
    regulador: "AGERGS",
    estados: JSON.stringify(["RS"]),
    extensaoKm: 271.54,
    situacao: "ATIVO",
    canalIsentos: "isentos@csg.com.br",
    tipoCanal: "EMAIL",
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa", "renavam"]),
  },
  {
    nome: "Rota de Santa Maria",
    grupo: "Sacyr",
    esfera: "ESTADUAL",
    regulador: "AGERGS",
    estados: JSON.stringify(["RS"]),
    rodovias: JSON.stringify(["RSC-287"]),
    extensaoKm: 204.51,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },

  // === MUNICIPAIS (2 registros) ===

  {
    nome: "LAMSA",
    grupo: "Invepar",
    esfera: "MUNICIPAL",
    regulador: "Prefeitura RJ",
    estados: JSON.stringify(["RJ"]),
    rodovias: JSON.stringify(["Linha Amarela"]),
    extensaoKm: 20,
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
  {
    nome: "Via Transolímpica",
    grupo: null,
    esfera: "MUNICIPAL",
    regulador: "Prefeitura RJ",
    estados: JSON.stringify(["RJ"]),
    rodovias: JSON.stringify(["Via Transolímpica"]),
    situacao: "ATIVO",
    canalIsentos: null,
    tipoCanal: null,
    ativoParaCadastro: true,
    camposObrigatorios: JSON.stringify(["placa"]),
  },
];
