// Dados completos de ~73 concessonárias conforme especificação
// Fonte: isenta-instrucoes-cadastro-concessionarias.md

export const concessionariasCompletas = [
  // FEDERAIS ANTT - 39 registros
  { nome: "Autopista Fluminense", grupo: "Arteris", esfera: "FEDERAL", regulador: "ANTT", estados: ["RJ"], extensaoKm: 322.10, situacao: "ATIVO" },
  { nome: "Autopista Litoral Sul", grupo: "Arteris", esfera: "FEDERAL", regulador: "ANTT", estados: ["SC", "PR"], extensaoKm: 409.40, situacao: "ATIVO" },
  { nome: "Autopista Planalto Sul", grupo: "Arteris", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR", "SC"], extensaoKm: 406.20, situacao: "ATIVO" },
  { nome: "Autopista Régis Bittencourt", grupo: "Arteris", esfera: "FEDERAL", regulador: "ANTT", estados: ["SP", "PR"], extensaoKm: 392.00, situacao: "ATIVO" },
  { nome: "CONCEBRA (Triunfo Concebra)", grupo: "Triunfo", esfera: "FEDERAL", regulador: "ANTT", estados: ["DF", "GO"], extensaoKm: 211.60, situacao: "ATIVO", observacoes: "Será relicitado como Rota do Pequi (ago/2026)" },
  { nome: "CONCER", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG", "RJ"], extensaoKm: 184.00, situacao: "CONTRATO_ENCERRADO" },
  { nome: "Ecovias Minas Goiás (Eco050)", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["GO", "MG"], extensaoKm: 433.20, situacao: "ATIVO", canalIsentos: "isentos@eco050.com.br", tipoCanal: "EMAIL", ativoParaCadastro: true },
  { nome: "Ecovias Capixaba", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["ES", "BA"], extensaoKm: 480.20, situacao: "ATIVO" },
  { nome: "Ecovias Ponte (Ecoponte)", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["RJ"], extensaoKm: 20.40, situacao: "ATIVO" },
  { nome: "Ecovias Rio Minas", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["RJ", "MG"], extensaoKm: 733.00, situacao: "ATIVO" },
  { nome: "Ecovias Sul (Ecosul)", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["RS"], extensaoKm: 456.40, situacao: "CONTRATO_ENCERRADO" },
  { nome: "Ecovias Araguaia", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["TO", "GO"], extensaoKm: 850.70, situacao: "ATIVO", canalIsentos: "isentos.araguaia@ecovias.com.br", tipoCanal: "EMAIL", ativoParaCadastro: true },
  { nome: "Ecovias Cerrado", grupo: "EcoRodovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG", "GO"], extensaoKm: 432.60, situacao: "ATIVO" },
  { nome: "Nova Rota do Oeste", esfera: "FEDERAL", regulador: "ANTT", estados: ["MT"], extensaoKm: 858.90, situacao: "ATIVO" },
  { nome: "RioSP (CCR RioSP)", grupo: "CCR", esfera: "FEDERAL", regulador: "ANTT", estados: ["SP", "RJ"], extensaoKm: 617.50, situacao: "ATIVO" },
  { nome: "Transbrasiliana", esfera: "FEDERAL", regulador: "ANTT", estados: ["SP"], extensaoKm: 323.60, situacao: "ATIVO" },
  { nome: "Via Brasil BR-163", esfera: "FEDERAL", regulador: "ANTT", estados: ["MT", "PA"], extensaoKm: 1001.20, situacao: "ATIVO" },
  { nome: "ViaCosteira (CCR ViaCosteira)", grupo: "CCR", esfera: "FEDERAL", regulador: "ANTT", estados: ["SC"], extensaoKm: 217.30, situacao: "ATIVO" },
  { nome: "ViaSul", grupo: "CCR", esfera: "FEDERAL", regulador: "ANTT", estados: ["RS"], extensaoKm: 465.30, situacao: "ATIVO" },
  { nome: "EPR Litoral Pioneiro", grupo: "EPR", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 604.16, situacao: "ATIVO", tipoCanal: "PORTAL_MAIS_ATENDIMENTO", observacoes: "Formulário no site + WhatsApp" },
  { nome: "Via Araucária", grupo: "EPR", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 471.68, situacao: "ATIVO", tipoCanal: "PORTAL_MAIS_ATENDIMENTO", observacoes: "Formulário no site + WhatsApp" },
  { nome: "Nova Dutra", grupo: "CCR", esfera: "FEDERAL", regulador: "ANTT", estados: ["SP", "RJ"], extensaoKm: 402.00, situacao: "CONTRATO_ENCERRADO" },
  { nome: "EPR Via Mineira", grupo: "EPR", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG"], extensaoKm: 232.10, situacao: "ATIVO" },
  { nome: "Motiva Paraná (ex-PRVias)", grupo: "Motiva", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 569.00, situacao: "ATIVO", canalIsentos: "isentos.ccrpagamentos.com.br", tipoCanal: "PORTAL_WEB", observacoes: "Confirmar se portal CCR/Motiva cobre", ativoParaCadastro: true },
  { nome: "Motiva Pantanal", grupo: "Motiva", esfera: "FEDERAL", regulador: "ANTT", estados: ["MS"], extensaoKm: 845.90, situacao: "ATIVO" },
  { nome: "Motiva Minas SP", grupo: "Motiva", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG", "SP"], extensaoKm: 569.10, situacao: "ATIVO" },
  { nome: "Nova 381", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG"], extensaoKm: 304.00, situacao: "ATIVO" },
  { nome: "Via Cristais", esfera: "FEDERAL", regulador: "ANTT", estados: ["GO", "MG"], extensaoKm: 594.80, situacao: "ATIVO" },
  { nome: "Way-262", grupo: "Way Brasil", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG"], extensaoKm: 440.60, situacao: "ATIVO", canalIsentos: "isento@way262.com.br", tipoCanal: "EMAIL", ativoParaCadastro: true },
  { nome: "Rota Verde Goiás", esfera: "FEDERAL", regulador: "ANTT", estados: ["GO"], rodovias: ["BR-060", "BR-452"], extensaoKm: 426.20, situacao: "ATIVO", observacoes: "Cobrança a partir de 2026. Rota crítica Goiânia-Brasília." },
  { nome: "EPR Iguaçu", grupo: "EPR", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 662.10, situacao: "ATIVO" },
  { nome: "Nova 364", esfera: "FEDERAL", regulador: "ANTT", estados: ["RO"], extensaoKm: 686.70, situacao: "ATIVO" },
  { nome: "Via Bahia", esfera: "FEDERAL", regulador: "ANTT", estados: ["BA"], extensaoKm: 676.00, situacao: "CONTRATO_ENCERRADO" },
  { nome: "VIA 040", grupo: "Invepar", esfera: "FEDERAL", regulador: "ANTT", estados: ["DF", "GO", "MG"], extensaoKm: 936.80, situacao: "CONTRATO_ENCERRADO", observacoes: "Assumida pelo DNIT; trecho Brasília-Cristalina em renegociação" },
  { nome: "Rodovia do Aço", esfera: "FEDERAL", regulador: "ANTT", estados: ["RJ"], extensaoKm: 182.50, situacao: "CONTRATO_ENCERRADO", observacoes: "Caducidade declarada" },
  { nome: "Elovias", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG", "RJ"], extensaoKm: 218.90, situacao: "ATIVO" },
  { nome: "EPR Paraná", grupo: "EPR", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 627.52, situacao: "ATIVO" },
  { nome: "Way-364 (Rota Agro)", grupo: "Way Brasil", esfera: "FEDERAL", regulador: "ANTT", estados: ["GO", "MT"], extensaoKm: 490.06, situacao: "ATIVO" },
  { nome: "Way-153 (Rota Sertaneja)", grupo: "Way Brasil", esfera: "FEDERAL", regulador: "ANTT", estados: ["MG", "GO"], extensaoKm: 530.60, situacao: "ATIVO" },
  { nome: "Via Campo", esfera: "FEDERAL", regulador: "ANTT", estados: ["PR"], extensaoKm: 432.70, situacao: "ATIVO" },

  // ESTADUAIS SP - ARTESP - 22 registros
  { nome: "AutoBAn", grupo: "CCR", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "TEBE", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Intervias", grupo: "Arteris", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Rota das Bandeiras", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Renovias", grupo: "CCR", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "ViaOeste", grupo: "CCR", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Colinas", grupo: "Via Appia", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "CART", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "ViaRondon", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "SPVias", grupo: "CCR", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Rodovias do Tietê", grupo: "Via Appia", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "EcoVias", grupo: "EcoRodovias", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "EcoPistas", grupo: "EcoRodovias", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "CCR RodoAnel", grupo: "CCR", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "SPMar", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Rodoanel Norte", grupo: "Via Appia", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Tamoios", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Entrevias", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "ViaPaulista", grupo: "Arteris", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "EixoSP", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "EcoNoroeste", grupo: "EcoRodovias", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },
  { nome: "Novo Litoral", esfera: "ESTADUAL", regulador: "ARTESP", estados: ["SP"], situacao: "ATIVO" },

  // ESTADUAIS MS - 2 registros
  { nome: "Way-306", grupo: "Way Brasil", esfera: "ESTADUAL", regulador: "Gov. MS", estados: ["MS"], rodovias: ["MS-306", "BR-359"], extensaoKm: 219.5, situacao: "ATIVO" },
  { nome: "Way-112", grupo: "Way Brasil", esfera: "ESTADUAL", regulador: "Gov. MS", estados: ["MS"], rodovias: ["MS-112", "BR-158", "BR-436"], extensaoKm: 412.4, situacao: "ATIVO" },

  // ESTADUAIS MT - 5+ registros
  { nome: "Via Brasil 246", esfera: "ESTADUAL", regulador: "Gov. MT (Sinfra)", estados: ["MT"], rodovias: ["MT-246", "MT-343", "MT-358"], extensaoKm: 233, situacao: "ATIVO" },
  { nome: "Rota dos Grãos", esfera: "ESTADUAL", regulador: "Gov. MT (Sinfra)", estados: ["MT"], rodovias: ["MT-130"], extensaoKm: 140.6, situacao: "ATIVO" },
  { nome: "Consórcio RDG Sinop (Lote 6 MT)", esfera: "ESTADUAL", regulador: "Gov. MT (Sinfra)", estados: ["MT"], rodovias: ["MT-020", "MT-140", "MT-225", "MT-244", "MT-251"], extensaoKm: 634.3, situacao: "ATIVO", observacoes: "Leiloado out/2025" },
  { nome: "Concessionária MT-100 (Lote 1)", esfera: "ESTADUAL", regulador: "Gov. MT (Sinfra)", estados: ["MT"], rodovias: ["MT-100"], extensaoKm: 111.9, situacao: "ATIVO", observacoes: "Nome da concessionária a confirmar" },
  { nome: "Concessionária MT-320/208 (Lote 2)", esfera: "ESTADUAL", regulador: "Gov. MT (Sinfra)", estados: ["MT"], rodovias: ["MT-320", "MT-208"], extensaoKm: 188.2, situacao: "ATIVO", observacoes: "Nome da concessionária a confirmar" },

  // ESTADUAIS RS - 3 registros
  { nome: "EGR (Empresa Gaúcha de Rodovias)", esfera: "ESTADUAL", regulador: "EGR/DAER", estados: ["RS"], extensaoKm: 630, situacao: "ATIVO", observacoes: "Pedágio público estadual, não concessionária privada. ~10-14 praças." },
  { nome: "CSG (Caminhos da Serra Gaúcha)", esfera: "ESTADUAL", regulador: "AGERGS", estados: ["RS"], extensaoKm: 271.54, situacao: "ATIVO", canalIsentos: "csg.com.br/isentos", tipoCanal: "PORTAL_WEB", ativoParaCadastro: true },
  { nome: "Rota de Santa Maria", grupo: "Sacyr", esfera: "ESTADUAL", regulador: "AGERGS", estados: ["RS"], rodovias: ["RSC-287"], extensaoKm: 204.51, situacao: "ATIVO" },

  // MUNICIPAIS RJ - 2 registros
  { nome: "LAMSA", grupo: "Invepar", esfera: "MUNICIPAL", regulador: "Prefeitura RJ", estados: ["RJ"], rodovias: ["Linha Amarela"], extensaoKm: 20, situacao: "ATIVO" },
  { nome: "Via Transolímpica", esfera: "MUNICIPAL", regulador: "Prefeitura RJ", estados: ["RJ"], rodovias: ["Via Transolímpica"], situacao: "ATIVO" },
];
